// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArzbB26iJxDcJ_ydBy4IpMbUjTmXL5LA',
    appId: '1:986362965075:web:afcca9afed2dab5f9ceaa6',
    messagingSenderId: '986362965075',
    projectId: 'recipebook-app-jsu-01',
    authDomain: 'recipebook-app-jsu-01.firebaseapp.com',
    storageBucket: 'recipebook-app-jsu-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIldqc8oIlJoYhe-F42nSnbARnpSXF68Q',
    appId: '1:986362965075:android:475c3bacb1853b429ceaa6',
    messagingSenderId: '986362965075',
    projectId: 'recipebook-app-jsu-01',
    storageBucket: 'recipebook-app-jsu-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLq97MCuKv7QYtBbVY6BKATDQKi-GbNBg',
    appId: '1:986362965075:ios:9a297538da955b5e9ceaa6',
    messagingSenderId: '986362965075',
    projectId: 'recipebook-app-jsu-01',
    storageBucket: 'recipebook-app-jsu-01.appspot.com',
    iosBundleId: 'com.example.recipebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLq97MCuKv7QYtBbVY6BKATDQKi-GbNBg',
    appId: '1:986362965075:ios:3d3851f1d366ed4a9ceaa6',
    messagingSenderId: '986362965075',
    projectId: 'recipebook-app-jsu-01',
    storageBucket: 'recipebook-app-jsu-01.appspot.com',
    iosBundleId: 'com.example.recipebook.RunnerTests',
  );
}
